#ifndef WIDGETS_H_INCLUDED
#define WIDGETS_H_INCLUDED
#include"Widget.h"
#include"GUI_Texture.h"
#include"GUI_Image.h"
#include"GUI_Text.h"
#include"GUI_BordererTexture.h"
#include"GUI_TextInPut.h"
#include"GUI_Button.h"
#include"GUI_InputNumber.h"
#include"GUI_SelectBox.h"
#include"GUI_Shape.h"
#include"GUI_svg.h"
#include"GUI_Panel.h"
#include"GUI_RadioButton.h"
#include"GUI_Table.h"
#include"GUI_CheckBox.h"
#include"GUI_ScrollBar.h"
#include"GUI_SidePanel.h"
#endif // WIDGETS_H_INCLUDED
